title: 프로그래머 나윤규의 웹사이트
author: 나윤규
email: nyk0806@naver.com
github_username: charles-na
facebook_username: YounKyuNa

show_excerpts: true
excerpt_separator: <!--more-->

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

google_analytics: UA-135516945-1
